source('R/01_setup.R')
source('R/03_data_cleaning.R')
source('R/04_return_calculation.R')
source('R/05_comparative_analysis.R')
source('R/06_representative_stock.R')
source('R/07_distribution_fitting.R')
source('R/08_goodness_of_fit.R')
source('R/09_hypothesis_testing.R')
source('R/10_extreme_returns.R')
source('R/11_clt_simulation.R')
source('R/12_monte_carlo.R')
source('R/13_portfolio_analysis.R')
source('R/14_var_analysis.R')
source('R/15_visualizations.R')
print('Smoke test completed successfully.')
